name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Mount Bazel cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel

      - name: Build
        run: bazel build //...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rules_mjml
          path: bazel-bin/distro/rules_mjml.tar.gz

  e2e:
    needs: build
    name: E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rules_mjml

      - name: Extract artifacts
        run: tar -xzf rules_mjml.tar.gz

      - name: Test
        run: cd e2e && bazel build //:simple
